### ISSUE TITLE
Move Ramda from devDeps to deps

### ISSUE THREAD

**Issue by Attrash-Islam** [Attrash-Islam/golden-path#2]

**Comment by ealush** [comment]
This would mean that consumers need to install both, and that you use it as an external. Not sure if that's the best approach for a library.

**Comment by Attrash-Islam** [comment]
No. Ramda is being tree-shaken in my bundle. So users won't need to use it implicitly and that won't affect anything regarding the bundle size or external configuration as well.

But I think that developers need to know what dependencies you count on in npm. This ticket is to make `golden-path` more transparent regarding its dependencies nothing more.

See this misleading screenshot from npm:
![image](https://user-images.githubusercontent.com/7091543/90341030-bb97cc00-e004-11ea-90c5-0d7b0a0df505.png)

WDYT @ealush ?

**Comment by ealush** [comment]
This is not what I mean.
By adding it to `dependencies` it can mean one of two things:

1. You put it in the dependencies, but still build it as a part of your bundle (after tree-shaking, of course). This means that your users will install Ramda for no reason - because they won't ever use it, neither will your code - so it just adds bloat to their node_modules folder.
2. You add it to the dependencies, and set your webpack config to use it as an external so it picks it up from your consumer node_modules. This puts the burden of bundling and tree shaking on your consumer - they can't just take `golden-path` and expect it to work out of the box (i.e as a script file).

Either way this is not very developer friendly in my opinion.

**Comment by Attrash-Islam** [comment]
I definitely against the second point for multiple reasons and I agree on redundantly adding Ramda to the node_modules. But how your package can be transparent if you do not state what dependency you're counting on. For example, maybe some TechLead for a company decided that we're not using any package that depends on Ramda for some reason, they won't be happy to find out that your npm dependencies is hiding this relationship. Did you get the point of my concern?

**Comment by ealush** [comment]
Package JSON and node modules in general is not a communication platform per se, it is there to declare the dependencies your package has in development (devDeps) time, and in production (deps) . You can also state which packages are counted as prerequisites (peerDeps) - but choosing each has actual implications.

If that hypothetical tech lead at that very hypothetical company needs to know what this package has inside - they are more than welcome to look at the code.
